name: mjx_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.11=h22baa00_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - aiofiles==25.1.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - astroid==4.0.1
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - azure-cognitiveservices-speech==1.46.0
      - azure-core==1.36.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - black==24.10.0
      - bleach==6.2.0
      - blinker==1.9.0
      - brax==0.13.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - chex==0.1.91
      - click==8.3.0
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.4.0
      - distlib==0.4.0
      - dm-control==1.0.34
      - dm-env==1.6
      - dm-tree==0.1.9
      - etils==1.13.0
      - execnet==2.1.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - flax==0.12.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - humanfriendly==10.0
      - humanize==4.13.0
      - identify==2.6.15
      - idna==3.11
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - immutabledict==4.2.2
      - importlab==0.8.1
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipykernel==7.0.0
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - isort==7.0.0
      - itsdangerous==2.2.0
      - jax==0.7.2
      - jax-cuda12-pjrt==0.7.2
      - jax-cuda12-plugin==0.7.2
      - jaxlib==0.7.2
      - jaxopt==0.8.5
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - lark==1.3.0
      - libcst==1.8.5
      - lxml==6.0.2
      - mapbox-earcut==1.0.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - media==0.1.6
      - mediapy==1.2.4
      - mistune==3.1.4
      - ml-collections==1.1.0
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - mujoco==3.4.0.dev818719010
      - mujoco-mjx==3.3.7
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - ninja==1.13.0
      - nodeenv==1.9.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - onnx==1.19.1
      - onnxruntime==1.23.1
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optax==0.2.6
      - orbax-checkpoint==0.11.25
      - orjson==3.11.3
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - playground==0.0.5
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==6.32.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycnite==2024.7.31
      - pycparser==2.23
      - pydantic==2.12.2
      - pydantic-core==2.41.4
      - pydot==4.0.1
      - pygments==2.19.2
      - pyink==24.10.1
      - pylint==4.0.0
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pytest==8.4.2
      - pytest-xdist==3.8.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytype==2024.10.11
      - pyvers==0.1.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - rsl-rl-lib==3.1.1
      - ruff==0.14.0
      - scipy==1.16.2
      - send2trash==1.8.3
      - sentry-sdk==2.41.0
      - shapely==2.1.2
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboardx==2.6.4
      - tensordict==0.10.0
      - tensorstore==0.1.78
      - terminado==0.18.1
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomlkit==0.13.3
      - toolz==1.0.0
      - torch==2.8.0
      - torchvision==0.23.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - treescope==0.1.10
      - trimesh==4.8.3
      - triton==3.4.0
      - types-python-dateutil==2.9.0.20251008
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uv==0.9.2
      - virtualenv==20.35.3
      - wandb==0.22.2
      - warp-lang==1.10.0.dev20251014
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - zipp==3.23.0
prefix: /home/kiwi/miniconda3/envs/mjx_env
